"use client";

import { useEffect, useState } from "react";

type Unit = { id: string; name: string; bedrooms: number; bathrooms: number; area_sqm: number | null; price_amount: number; currency: string; available_date: string | null };
type Property = { id: string; name: string; neighborhood: string; kind: string; listing_type: "rent" | "sale"; price_amount: number; currency: string; bedrooms: number; bathrooms: number; area_sqm: number | null; year_built: number | null; address: string; city: string; description: string; images: { id: string; alt_text: string; url: string }[]; units: Unit[] };
const money = (amount: number, currency: string) => new Intl.NumberFormat("en", { style: "currency", currency, maximumFractionDigits: 0 }).format(amount);

export default function ListingDetail({ params }: { params: Promise<{ id: string }> }) {
  const [property, setProperty] = useState<Property | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { void params.then(({ id }) => fetch("/api/listings/" + id).then((response) => response.json().then((body) => ({ response, body }))).then(({ response, body }) => { if (!response.ok) throw new Error(body.error); setProperty(body.property); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Listing unavailable."))); }, [params]);
  if (error) return <main className="marketplace"><MarketHeader /><section className="market-empty detail-empty"><strong>{error}</strong><a className="button button-dark" href="/discover">Browse homes</a></section></main>;
  if (!property) return <main className="marketplace"><MarketHeader /><section className="market-empty detail-empty"><strong>Loading listing…</strong></section></main>;
  const mainImage = property.images[0];
  return <main className="marketplace"><MarketHeader /><section className="detail-hero"><div className="detail-image">{mainImage ? <img src={mainImage.url} alt={mainImage.alt_text || property.name} /> : <span className="listing-fallback"><i /><i /><i /></span>}</div><div className="detail-summary"><p className="kicker">{property.listing_type === "rent" ? "HOME FOR RENT" : "HOME FOR SALE"}</p><h1>{property.name}</h1><p className="detail-location">{property.address}, {property.neighborhood} · {property.city}</p><strong>{property.price_amount ? money(property.price_amount, property.currency) : "Price on request"}{property.listing_type === "rent" && property.price_amount ? <small> / month</small> : null}</strong><div className="detail-specs"><span>{property.bedrooms || "—"}<small>Bedrooms</small></span><span>{property.bathrooms || "—"}<small>Bathrooms</small></span><span>{property.area_sqm || "—"}<small>m²</small></span>{property.year_built && <span>{property.year_built}<small>Built</small></span>}</div><a className="button button-dark" href={"/apply?listing=" + property.id}>Apply for this home <span>→</span></a></div></section><section className="listing-body"><article><p className="kicker">ABOUT THIS HOME</p><h2>Made for everyday living.</h2><p>{property.description || "Contact the property team to learn more about this home and its available units."}</p></article><aside><p className="kicker">AVAILABLE UNITS</p>{property.units.length ? property.units.map((unit) => <div className="unit-row" key={unit.id}><div><strong>{unit.name}</strong><span>{unit.bedrooms} bd · {unit.bathrooms} ba{unit.area_sqm ? " · " + unit.area_sqm + " m²" : ""}</span></div><b>{money(unit.price_amount, unit.currency)}</b></div>) : <p className="unit-empty">Contact the property team for current unit availability.</p>}</aside></section></main>;
}

function MarketHeader() { return <header className="market-header"><a className="brand" href="/"><span className="brand-mark"><i /><i /><i /></span><span>urugo</span></a><nav><a className="nav-active-link" href="/discover">Explore homes</a><a href="/apply">Apply</a><a href="/contact">Contact</a><a className="button button-light" href="/">Sign in</a></nav></header>; }
