export type Facility = {
  id: string;
  name: string;
  kind: string;
  city: string;
  address: string;
  phone: string;
  hours: string;
  status: string;
  license?: string;
  review_note?: string;
  verified_at?: string;
  can_manage_team?: number;
};
export type Medicine = {
  id: string;
  facility_id: string;
  name: string;
  generic_name: string;
  strength: string;
  form: string;
  availability: string;
  updated_at: string;
  stale?: number;
  facility_name: string;
  city: string;
  address: string;
  phone: string;
  hours: string;
};
export type Slot = {
  id: string;
  facility_id: string;
  facility_name: string;
  service: string;
  practitioner: string;
  starts_at: string;
  ends_at: string;
  status: string;
  city: string;
  address: string;
  phone: string;
};
export type MedicineRequest = {
  id: string;
  status: string;
  facility_id: string;
  facility_name: string;
  name: string;
  strength: string;
  form: string;
  patient_name: string;
  created_at: string;
  hold_until: string | null;
  phone: string;
  address: string;
  city: string;
  facility_status?: string;
};
export type Appointment = {
  id: string;
  status: string;
  facility_id: string;
  facility_name: string;
  service: string;
  practitioner: string;
  starts_at: string;
  ends_at: string;
  patient_name: string;
  created_at: string;
  phone: string;
  address: string;
  city: string;
  facility_status?: string;
};
export type HealthWorkspace = {
  facilities: Facility[];
  inventory: Medicine[];
  slots: Slot[];
  requests: MedicineRequest[];
  appointments: Appointment[];
  mine: MedicineRequest[];
  bookings: Appointment[];
  review: Facility[];
  staff: {
    id: string;
    facility_id: string;
    display_name: string;
    email: string;
    status: string;
  }[];
  isAdmin: boolean;
};
